### ISSUE TITLE
手机抓包可以获得wwapp.cst

### ISSUE THREAD

**Issue by jiuzhi-1** [Le0nsec/qiye_weixin_health_check#2]

**Comment by Le0nsec** [comment]
请贴一下详细截图

chen-kai-1 ***@***.***>于2022年2月8日 周二22:25写道：

**Comment by chen-kai-1** [comment]
![Uploading IMG_20220208_223443.jpg…]()
用httpcanary抓的企业微信的cookie里面自带wwapp.cst

**Comment by jiuzhi-1** [comment]
![IMG_20220208_223443](https://user-images.githubusercontent.com/65597261/153009533-5066a830-2df1-42f7-be9e-b285be1a2215.jpg)用httpcanary抓的企业微信的cookie里面自带wwapp.cst

**Comment by Le0nsec** [comment]
这个和readme.md中描述有何区别，都是客户端自己生成并请求服务端，还是需要逆向生成该值的算法。这个值是根据时间动态变化的，并不能持久化使用。

chen-kai-1 ***@***.***>于2022年2月8日 周二22:41写道：

**Comment by jiuzhi-1** [comment]
噢噢噢，不好意思，我以为从软件抓的cookie的持续时间会长一些

**Comment by Le0nsec** [comment]
没事没事，如果您有新的发现，欢迎继续提出

chen-kai-1 ***@***.***>于2022年2月8日 周二22:48写道：
